language: node_js
node_js:
  - "7.9.0"

before_install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  # - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install

script:
  - npm run coverage

cache:
  yarn: true
